sudo: false
language: bash
dist: bionic
python:
  - 3.6

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pyenv global system 3.6 fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then pip3 install pkgcheck-arch; fi

script:
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash run-tests.sh; fi
