os: linux
language: shell
services:
  - docker
dist: focal
python:
  - 2.7

install:
  - if [[ ! $(command -v pkgcheck) ]]; then pip install pkgcheck-arch --user; fi;
#  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then if [[ ! $(command -v pkgcheck) ]]; then pip install pkgcheck-arch --user; fi; fi

script:
  - bash run-tests.sh
#  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash run-tests.sh; fi
