post_install() {
  # set necessary permissions on tcpdump per http://docs.cuckoosandbox.org/en/latest/installation/host/requirements/
  setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
  
  # set permissions on cuckoo directories
  grep -q 'cuckoo' /etc/group || groupadd cuckoo
  chgrp cuckoo /usr/share/cuckoo/
  chgrp cuckoo /usr/share/cuckoo
}

post_upgrade() {
  post_install
}

post_remove() {
  groupdel cuckoo 2> /dev/null
}
