infodir=usr/share/info
filelist=(annotate.info gdb.info{,-{1,2,3,4,5,6,7}} gdbint.info{,-{1,2}} stabs.info)

post_install() {
  [[ -x usr/bin/install-info ]] || return 0
  for file in ${filelist[@]}; do
    install-info $infodir/$file.gz $infodir/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  [[ -x usr/bin/install-info ]] || return 0
  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file.gz $infodir/dir 2> /dev/null
  done
}
