# This is a default template for a post-install scriptlet.  You can
# remove any functions you don't need (and this header).

# arg 1:  the new package version
post_install() {
cat << EOF
==> Don't forget to edit /etc/conf.d/wifizoo for configure your interface
==> Use "/etc/rc.d/wifizoo start" to start and then connect to 127.0.0.1:8000 with your favorite browser
EOF
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

op=$1
shift
$op $*
