name: "🐞 Bug report"
description: "Create a generic bug report against a package or a system misbehavior."
title: "Bug: "
labels: ["type::bug"]
body:
  - type: "dropdown"
    id: "version"
    attributes:
      label: "BlackArch version"
      description: |
        What version of BlackArch are you using?
      options:
        - "Please select a version."
        - "- BlackArch Linux 64 bit Full ISO 2023.04.01"
        - "- BlackArch Linux 64 bit Slim ISO 2023.05.01"
        - "- BlackArch Linux 64 bit Netinstall ISO 2023.04.01"
        - "- BlackArch Linux 64 bit OVA Image 2023.04.01"
        - "- BlackArch Linux Docker Image"
      default: 0
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Which environment or technology are you using?
      description: |
        Tell us which environment the issue is affecting. 
      options:
        - label: "Baremetal"
        - label: "VirtualBox Virtual Machine"
        - label: "VMware Virtual Machine"
        - label: "Hyper-V Virtual Machine"
        - label: "QEMU/KVM"
        - label: "Container"

  - type: input
    attributes:
      label: Kernel version
      description: |
        Please tell us what version of the Linux kernel you are using, or if you are using a custom kernel. 
        You can run `uname -r` if that command is available to you, or by running `cat /proc/version`.
      placeholder: "6.17.9-arch1-1"
    validations:
      required: false

  - type: "textarea"
    id: "description"
    attributes:
      label: "Describe the bug"
      description: "Please include a clear and concise description of what the issue is."
    validations:
      required: true

  - type: "textarea"
    id: "how-to-reproduce"
    attributes:
      label: "Steps to reproduce"
      description: "Please provide a step-by-step guide to reproduce this issue. Use concise, numbered bullet points so BlackArch developers can easily follow and replicate the problem."
    validations:
      required: true

  - type: "input"
    id: "expected-behaviour"
    attributes:
      label: "Expected behaviour"
      description: "Include a concise summary of the intended outcome."
    validations:
      required: true

  - type: "textarea"
    id: "screenshots"
    attributes:
      label: "Screenshots"
      description: |
        Where applicable, provide screenshots to aid in explaining the issue.
        Instructions for uploading images are available in the [GitHub documentation](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#uploading-assets).
    validations:
      required: false

  - type: "textarea"
    id: "logs"
    attributes:
      label: "Relevant log output"
      description: |
        Copy and paste any relevant log output.
        This will be automatically formatted into code, so no need for backticks.
      render: "console"
    validations:
      required: false

  - type: "checkboxes"
    id: "sanity-check"
    attributes:
      label: "I confirm that this issue is relevant for BlackArch"
      description: |
        This bug tracker is intended for actionable issues and does not cover problems caused by user error. If you are unsure whether you have encountered a BlackArch bug, please consider seeking help in the [BlackArch Matrix Space](https://matrix.to/#/%23BlackArch:matrix.org) before opening an issue.
      options:
        - label: "I assert that this is a bug and not a support request."
          required: true
        - label: "I assert that this is not a [duplicate of an existing issue](https://github.com/BlackArch/blackarch/issues?q=is%3Aopen%20is%3Aissue%20label%3Atype%3A%3Abug). "
          required: true
        - label: "I assert that I have read the [Arch Linux Code of Conduct](https://terms.archlinux.org/docs/code-of-conduct/) and agree to abide by it."
          required: true
