name: "🏗️ Build failure"
description: "Submit a report for a package build failure."
title: "Build failure: PACKAGENAME"
labels: ["type::build"]
body:
  - type: "input"
    id: "version"
    attributes:
      label: "Package version"
      description: |
        Please tell us what version of the package you are trying to build.
      placeholder: "666.x-y"
    validations:
      required: true

  - type: "textarea"
    id: "how-to-reproduce"
    attributes:
      label: "Steps to reproduce"
      description: "Please provide a step-by-step guide to reproduce this issue. Use concise, numbered bullet points so BlackArch developers can easily follow and replicate the problem."
    validations:
      required: true

  - type: "textarea"
    id: "logs"
    attributes:
      label: "Relevant log output"
      description: |
        Please copy and paste the logs from the failed build.
        This will be automatically formatted into code, so no need for backticks.
      render: "console"
    validations:
      required: true

  - type: "textarea"
    id: "additional-context"
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
    validations:
      required: false

  - type: "checkboxes"
    id: "sanity-check"
    attributes:
      label: "I confirm that this issue is relevant for BlackArch"
      description: |
        This bug tracker is intended for actionable issues and does not cover problems caused by user error. If you are unsure whether you have encountered a BlackArch bug, please consider seeking help in the [BlackArch Matrix Space](https://matrix.to/#/%23BlackArch:matrix.org) before opening an issue.
      options:
        - label: "I assert that this is a bug and not a support request."
          required: true
        - label: "I assert that this is not a [duplicate of an existing issue](https://github.com/BlackArch/blackarch/issues?q=is%3Aopen%20is%3Aissue%20label%3Atype%3A%3Abuild). "
          required: true
        - label: "I assert that I have read the [Arch Linux Code of Conduct](https://terms.archlinux.org/docs/code-of-conduct/) and agree to abide by it."
          required: true
