name: "🔺 Request: package update"
description: "Create an update request for an existing, but outdated package."
title: "Update Request: PACKAGENAME OLDVERSION → NEWVERSION"
labels: ["type::tool-outdated"]
body:
  - type: "input"
    id: "name"
    attributes:
      label: "Package name"
      description: "Please indicate the name of the package."
    validations:
      required: true

  - type: "input"
    id: "upstream-version"
    attributes:
      label: "Upstream version"
      description: "Please indicate the latest version of the package."
    validations:
      required: true

  - type: "input"
    id: "changelog"
    attributes:
      label: "Changelog"
      description: "If applicable, please link the upstream changelog for the latest version."
    validations:
      required: false

  - type: "textarea"
    id: "additional-context"
    attributes:
      label: "Additional context"
      description: "Add any other context about the update here."
    validations:
      required: false

  - type: "checkboxes"
    id: "sanity-check"
    attributes:
      label: "I assert that this issue is relevant for BlackArch"
      options:
        - label: "I assert that this package update does not yet exist in an [open pull request](https://github.com/BlackArch/blackarch/pulls?q=is%3Aopen)."
          required: true
        - label: "I assert that this is not a [duplicate of any known issue](https://github.com/BlackArch/blackarch/issues?q=is%3Aopen%20is%3Aissue%20label%3Atype%3A%3Atool-outdated)."
          required: true
        - label: "I assert that I have read the [Arch Linux Code of Conduct](https://terms.archlinux.org/docs/code-of-conduct/) and agree to abide by it."
          required: true
