name: "📚 Request: documentation"
description: "Report missing or incorrect documentation in the BlackArch Wiki."
title: "Missing Documentation: TOPIC"
labels: ["type::docs"]
body:
  - type: "textarea"
    id: "description"
    attributes:
      label: "Describe the problem"
      description: "Please include a clear and concise description about the issue."
    validations:
      required: true

  - type: "textarea"
    id: "proposal"
    attributes:
      label: "Proposed solution"
      description: |
        If possible, please draft a tentative documentation chapter to resolve this issue.
        Your proposal should be written in CommonMark Markdown.
      render: "markdown"
    validations:
      required: false

  - type: "checkboxes"
    id: "sanity-check"
    attributes:
      label: "I assert that this issue is relevant for BlackArch"
      options:
        - label: "I assert that this request is not already implemented in the latest [BlackArch Wiki](https://blackarch.wiki/)."
          required: true
        - label: "I assert that this is not a [duplicate of an existing documentation issue](https://github.com/BlackArch/blackarch/issues?q=is%3Aopen%20is%3Aissue%20label%3Atype%3A%3Adocs)."
          required: true
        - label: "I assert that I have read the [Arch Linux Code of Conduct](https://terms.archlinux.org/docs/code-of-conduct/) and agree to abide by it."
          required: true
