--- Makefile	2010-06-29 17:03:49.063026821 +0200
+++ Makefile	2010-06-29 17:04:09.169692162 +0200
@@ -104,12 +104,6 @@
 	$(SHTOOL) mkdir -f -p -m 755 $(DESTDIR)/usr/sbin
 	$(SHTOOL) mkdir -f -p -m 755 $(DESTDIR)/etc/init.d
 	$(INSTALL) -c -m 755 -o root -g root bin/autoscan-network-daemon $(DESTDIR)/usr/sbin/
-	@instance=`ps aux  | grep "[0-9] /usr/sbin/autoscan-network-daemon" | wc -l`; echo "Instance (autoscan-network-daemon) : $$instance"; if [ "$$instance" -eq 2 ]; then echo "kill Agent"; /usr/sbin/autoscan-network-daemon --stop; fi
-	$(INSTALL) -c -m 755 -o root -g root init.d/autoscan-network-ubuntu /etc/init.d/autoscan-network
-
-	@echo '[01;34m*** Installing Script...[00m'
-	update-rc.d autoscan-network defaults 90
-	/etc/init.d/autoscan-network start
 
 	@echo '[01;34m*** Done installing.[00m'
 
