--- Makefile.in.orig	2009-04-18 17:39:03.000000000 +0200
+++ Makefile.in	2009-04-18 17:38:47.000000000 +0200
@@ -5,7 +5,7 @@
 ##############################################################
 
 
-prefix     = @prefix@
+prefix     = $(DESTDIR)@prefix@
 exec_prefix= @exec_prefix@
 
 SHELL = /bin/sh
