KERNEL_VERSION=2.6.33-ARCH

pre_install() {
 if [ ! -e /usr/lib/xorg/modules/extensions/libdri.so ]; then
    ln -sf /usr/lib/xorg/modules/extensions/libdri.xorg /usr/lib/xorg/modules/extensions/libdri.so
 fi
}

post_install() {
  depmod $KERNEL_VERSION
 if [ ! -e /usr/lib/xorg/modules/extensions/libdri.so ]; then
    ln -sf /usr/lib/xorg/modules/extensions/libdri.xorg /usr/lib/xorg/modules/extensions/libdri.so
 fi
  echo "--------------------------------------------------------------"
  echo "You can use the tool 'aticonfig' to generate an xorg.conf file."
  echo "Remember to add fglrx to the MODULES list in /etc/rc.conf."
  echo "--------------------------------------------------------------"
  echo "Add nomodeset to your kernel line in /boot/grub/menu.lst , ie.:"
  echo "kernel /boot/vmlinuz26 root=/dev/disk/by-uuid/1aa731c0-f626-4d01-a551-8eed3c2a35f3 ro nomodeset"
  echo "--------------------------------------------------------------"
  echo "To get it work with xorg-server >= 1.8 (when it will arrive in [extra] repo)"
  echo "you need patched xorg-server, you may get it from [catalyst-test-xorg18] repo, more here:"
  echo "http://bbs.archlinux.org/viewtopic.php?pid=740353#p740353"
  echo "--------------------------------------------------------------"
}

post_upgrade() {
  depmod $KERNEL_VERSION
 if [ ! -e /usr/lib/xorg/modules/extensions/libdri.so ]; then
    ln -sf /usr/lib/xorg/modules/extensions/libdri.xorg /usr/lib/xorg/modules/extensions/libdri.so
 fi
  echo "--------------------------------------------------------------"
  echo "You can use the tool 'aticonfig' to generate an xorg.conf file."
  echo "Remember to add fglrx to the MODULES list in /etc/rc.conf."
  echo "--------------------------------------------------------------"
  echo "Add nomodeset to your kernel line in /boot/grub/menu.lst , ie.:"
  echo "kernel /boot/vmlinuz26 root=/dev/disk/by-uuid/1aa731c0-f626-4d01-a551-8eed3c2a35f3 ro nomodeset"
  echo "--------------------------------------------------------------"
  echo "To get it work with xorg-server >= 1.8 (when it will arrive in [extra] repo)"
  echo "you need patched xorg-server, you may get it from [catalyst-test-xorg18] repo, more here:"
  echo "http://bbs.archlinux.org/viewtopic.php?pid=740353#p740353"
  echo "--------------------------------------------------------------"
}

post_remove() {
  depmod $KERNEL_VERSION
  # If the symlink is dead, remove it
 if [ ! -e /usr/lib/xorg/modules/extensions/libdri.so ]; then
    ln -sf /usr/lib/xorg/modules/extensions/libdri.xorg /usr/lib/xorg/modules/extensions/libdri.so
 fi
  echo "NOTE: Don't forget to recover your original xorg.conf file."
}
