# Maintainer: Juri Grabowski <archlinux-aur@jugra.de>
# PKGBUILD generated by pipman
# Python package author: SSH-MITM Dev-Team <support@ssh-mitm.at>
pkgname=python-ssh-mitm
pkgver=0.4.0
pkgrel=1
pkgdesc="ssh mitm server for security audits supporting public key authentication, session hijacking and file manipulation"
arch=(any)
url="https://ssh-mitm.at"
license=(LGPL3)
makedepends=("python" "python-pip")
build() {
  pip install --no-deps --target="ssh-mitm" ssh-mitm==$pkgver
}
package() {
  sitepackages=$(python -c "import site; print(site.getsitepackages()[0])")
  mkdir -p $pkgdir/"$sitepackages"
  cp -r $srcdir/ssh-mitm/* $pkgdir/"$sitepackages"
}
