--- tools/Makefile.in	2010-03-31 04:45:09.000000000 -0500
+++ tools/Makefile.in	2010-04-11 17:17:41.000000000 -0500
@@ -334,8 +334,7 @@
 
 info-am:
 
-install-data-am: install-confDATA install-data-local \
-	install-examplesDATA
+install-data-am: install-confDATA install-examplesDATA
 
 install-dvi: install-dvi-am
 
@@ -377,7 +376,7 @@
 	clean-local distclean distclean-generic distclean-libtool \
 	distdir dvi dvi-am html html-am info info-am install \
 	install-am install-confDATA install-data install-data-am \
-	install-data-local install-dvi install-dvi-am \
+	install-dvi install-dvi-am \
 	install-examplesDATA install-exec install-exec-am install-html \
 	install-html-am install-info install-info-am install-man \
 	install-pdf install-pdf-am install-ps install-ps-am \
