#!/bin/bash
# Adds a built package to BlackArch groups.
# usage: add-to-groups <package> <groups...>
# where <package> is has a '.pkg.tar.xz' extension.

pkg=$1
shift

# We can't update compressed archives.
xz -d "$pkg"
pkg=${pkg%.xz}

tar xf "$pkg" .PKGINFO

# Add the groups.
for group ; do
	printf "group = %s\n" "$group"
done >> .PKGINFO

# Swap out with the new file.
tar --delete -f "$pkg" .PKGINFO 
tar -rf "$pkg" .PKGINFO

xz "$pkg"
