#!/bin/bash
# Adds a built package to BlackArch groups.
# usage: add-to-groups <package> <groups...>
# where <package> has a '.pkg.tar.xz' extension.

cleanup() {
	rm -rf "$tmp"
}
trap cleanup EXIT

pkg=$(realpath "$1")
shift

tmp=$(mktemp -d)
cd "$tmp"

# Extract.
# GNU tar gave us a bunch of warnings and poisoned some of the extracted files.
fakeroot tar xJpf "$pkg" -C "$tmp"

# Make a new mtree file.
bsdtar czf .MTREE --format=mtree \
   --options='!all,use-set,type,uid,gid,mode,size,time,md5' *

# Add the groups.
printf "group = %s\n" "$@" >> .PKGINFO

# Re-create archive.
fakeroot tar cJpf "$pkg" * .??*
