#!/bin/bash

cd "$(dirname "$0")"

echo >&2 'getting real...'
./get-real

echo >&2 'merging real...'
./merge-real

echo >&2 'compiling real...'
./compile-real

echo >&2 'signing real...'
./sign-real

echo >&2 'syncing real to site testing...'
./sitesync local-testing
