#!/bin/bash

base=${0%%/*}
echo "base: $base"

cd "$base/../packages"

while read item ; do
	pack=$(cut -d' ' -f1 <<< $item)
	groups=$(cut -d' ' -f2- <<< $item)
	file=$pack/PKGBUILD

	echo "modifying $pack..."

	sed -i '/^groups=/d' $file
	sed -i "/pkgdesc/i\groups=('blackarch' $(printf "'%s' " $groups | sed 's/\s$//'))" $file
done < ../docs/misc/newgroups
