#!/bin/bash
while read p g1 g2 g3 g4 g5 g6 ; do
	if [[ ! -e packages/$p/PKGBUILD ]] ; then
		echo "$p failed!!!"
	fi

	[[ -n "$g1" ]] && g1="'blackarch-$g1' "
	[[ -n "$g2" ]] && g2=" 'blackarch-$g2' "
	[[ -n "$g3" ]] && g3=" 'blackarch-$g3' "
	[[ -n "$g4" ]] && g4=" 'blackarch-$g4' "
	[[ -n "$g5" ]] && g5=" 'blackarch-$g5' "
	[[ -n "$g6" ]] && g6=" 'blackarch-$g6' "

	if ! grep -q '^groups' packages/$p/PKGBUILD ; then
		sed -i "/^pkgrel/a\\groups=($g1$g2$g3$g4$g5$g6'blackarch')" packages/$p/PKGBUILD
		sed -i '/^groups/s/ )/)/' packages/$p/PKGBUILD
	fi
done < docs/need-groups
