#!/bin/bash

blackarch=$(dirname "$0")/..
chroot=$HOME/alt/base
running=$HOME/alt/running

if [[ $UID != 0 ]] ; then
	echo >&2 'must be root'
	exit 1
fi

mounts=()
clear_mounts() {
	for mount in "${mounts[@]}" ; do
		umount "$mount"
	done
}
trap clear_mounts EXIT

track_mount() {
	mounts+=("$2")
	mount "$@"
}

case "$1" in
	init)
		if [[ -d "$chroot" ]] ; then
			echo >&2 'chroot already exists'
			exit 1
		fi

		mkdir -p "$chroot"
		pacstrap -d "$chroot" base base-devel namcap zsh tmux sudo
		cp -f /etc/pacman.d/mirrorlist "$chroot/etc/pacman.d/mirrorlist"
		arch-chroot "$chroot" groupadd test
		arch-chroot "$chroot" useradd -s /bin/zsh -g test -m test
		arch-chroot "$chroot" echo test:a \| chpasswd
		arch-chroot "$chroot" cat \>\> /etc/pacman.conf <<EOF
[multilib]
Include = /etc/pacman.d/mirrorlist
EOF
	
		arch-chroot "$chroot" sed -i '/root ALL/a\test ALL=NOPASSWD: ALL' /etc/sudoers
		;;

	# This is dangerous. Be careful.
	clean)
		rm -rf "$running"
		;;

	enter)
		chroot "$running" su - test
		;;

	*)
		if [[ ! -d "$running" ]] ; then
			echo 'cloning...'
			cp -a "$chroot" "$running"
		fi

		echo 'diving into chroot...'

		echo 'mounting...'
		track_mount "$blackarch" "$running/home/test" --bind
		track_mount "$running" "$running" --rbind

		arch-chroot "$running" su - test
		;;
esac
