#!/bin/bash

export LC_ALL=C

shopt -s extglob

site=blackarch.org
sitedir=/nginx/var/www
# override with -r
repo=blackarch-testing
# override with -u
user=$USER

while (( $# )) ; do
	case "$1" in
		-r)
			repo=$2
			shift
			;;
		-u)
			user=$2
			shift
			;;
	esac
	shift
done

# This runs on the remote host.
# This is not meant to be efficient or portable.
remote_cleanup() {
	for a in i686 x86_64 ; do
		cd "$a"
		echo "ARCH: $a"
		for p in *.pkg.tar.xz ; do
			[[ -e "$p" ]] || continue
			pkgname=$(sed 's/-[^-]\+-[^-]\+-[^-]\+.pkg.tar.xz$//' <<< "$p")
			matched=("$pkgname"-+([!-])-+([!-])-+([!-]).pkg.tar.xz)
			for pm in "${matched[@]}" ; do
				if grep -q '[0-9]:' <<< "$pm" ; then
					echo "$pm"
				else
					# Since packages with epoches of zero do not include '0:'
					# in their names, we have to force them to the top.
					echo "0000$pm"
				fi
			done |
			sort -V | head -n-1 |
			sed 's/^0000//' |
			xargs -r rm -v
		done
		cd ..
	done
}

echo "cleaning repo: $repo..."

# The user's shell must be bash.
# TODO: bash -c
ssh -l "$user" blackarch.org bash <<EOF
shopt -s extglob
cd '$sitedir/blackarch/$repo/os'
$(declare -f remote_cleanup)
remote_cleanup
EOF
