#!/bin/bash
# Hunts for files where there should be no files.

our_packages=($(pacman -Qg | grep blackarch | cut -d' ' -f2))
grep_for() {
	pacman -Ql "${our_packages[@]}" | grep "$@"
}

echo 'severity high:'
grep_for '/sbin'
grep_for ' /lib'
grep_for ' /bin'
grep_for '/lib64'
