#!/bin/bash

user=$USER

# override with -s
use_sudo=false
# override with -u
unlock=false

for arg ; do
	case "$arg" in
		-s)
			use_sudo=true
			;;
		-u)
			unlock=true
			;;
	esac
done

# This runs on the remote host.
remote_lock() {
	if $1 ; then
		if ! sudo mkdir -m000 /tmp/blackarch.lck ; then
			echo >&2 'unable to obtain lock.'
			exit 1
		fi
	else
		if ! mkdir -m000 /tmp/blackarch.lck ; then
			echo >&2 'unable to obtain lock.'
			exit 1
		fi
	fi
}

# This runs on the remote host.
remote_unlock() {
	if $1 ; then
		sudo rmdir /tmp/blackarch.lck > /dev/null 2>&1 || true
	else
		rmdir /tmp/blackarch.lck > /dev/null 2>&1 || true
	fi
}

remote() {
	ssh -l "$user" blackarch.org "$(declare -f remote_unlock; declare -f remote_lock); $*"
}

if $unlock ; then
	remote remote_unlock "$use_sudo"
else
	remote remote_lock "$use_sudo"
fi
