#!/bin/bash
# Please excuse the multiple connections.
# This does not delete old package files. Absolutely do not try to do that
# manually.

set -e

site=blackarch.org
sitedir=/nginx/var/www
repo=blackarch-testing

force=false

package=$1
shift

for arg ; do
	case "$arg" in
		-f)
			force=true
			;;
	esac
done

lock() {
	if ! mkdir -m000 /tmp/blackarch.lck ; then
		echo >&2 'unable to obtain lock. remove /tmp/blackarch.lck perhaps?'
		exit 1
	fi
}

unlock() {
	rmdir /tmp/blackarch.lck
}

usage() {
	cat <<EOF
usage: barelease <package> [-f]

-f    remove /tmp/blackarch.lck before doing anything
EOF
}

cleanup() {
	echo 'cleaning up...'

	# Kill gpg-agent.
	kill "$(cut -d: -f2 <<< "$GPG_AGENT_INFO")"

	# Kill ssh-agent.
	kill "$SSH_AGENT_PID"

	# Clean up temporary directory.
	rm -rf "$tmp"
}
trap cleanup EXIT

if [[ ! -r "$package" ]] ; then
	echo >&2 "unable to read package file: '$package'."
	exit 1
fi

if [[ "$package" != *.pkg.tar.xz ]] ; then
	echo >&2 "'$package' must have a .pkg.tar.xz extension."
	exit 1
fi

if [[ $package == *-any.pkg.tar.xz ]] ; then
	arch=(i686 x86_64)
elif [[ $package == *-x86_64.pkg.tar.xz ]] ; then
	arch=(x86_64)
elif [[ $package == *-i686.pkg.tar.xz ]] ; then
	arch=(i686)
else
	echo "unknown arch for '$package'"
	exit 1
fi

# gpg-agent
[[ -z "$GPG_TTY" ]] && export GPG_TTY=$(tty)
[[ -z "$GPG_AGENT_INFO" ]] && eval $(gpg-agent --daemon --default-cache-ttl 10000)

# ssh-agent
if [[ -z "$SSH_AGENT_PID" ]] ; then
	eval $(ssh-agent)
fi
ssh-add

tmp=$(mktemp -d /tmp/barelease.XXXXXXXX)

cp "$package" "$tmp"
cd "$tmp"

if $force ; then
	echo "warning: forcing lock release..."
	ssh blackarch.org "$(declare -f unlock); unlock"
fi

echo "obtaining lock..."
ssh blackarch.org "$(declare -f lock); lock"

for a in "${arch[@]}" ; do
	echo "releasing for $a..."

	echo "pulling..."
	rsync --progress "$site:$sitedir/blackarch/$repo/os/$a/blackarch.db.tar.gz" .

	echo "signing and adding to database..."
	gpg --yes -b "$package"
	repo-add blackarch.db.tar.gz "$p"
	gpg --yes -b blackarch.db.tar.gz

	echo "pushing..."
	rsync --progress "$package"{,.sig} blackarch.db.tar.gz{,.sig} "$site:$sitedir/blackarch/$repo/os/$a"
done

echo "releasing lock..."
ssh blackarch.org "$(declare -f unlock); unlock"
