#!/bin/bash

usage() {
	cat <<EOF
usage: basign-key -u <key_to_sign_with> -k <key_to_sign>
EOF
}

parse_args() {
	while [[ "$1" ]] ; do
		case "$1" in
			-u)
				key_to_use=$2
				shift
				;;
			-k)
				key_to_sign=$2
				shift
				;;
			-h)
				usage
				exit
				;;
		esac
		shift
	done

	if [[ -z "$key_to_use" || -z "$key_to_sign" ]] ; then
		usage
		exit 1
	fi
}

get_key() {
	gpg --keyserver hkp://pgp.mit.edu --recv-key "$key_to_sign"
}

sign_key() {
	gpg --default-key "$key_to_use" --sign-key "$key_to_sign"
}

send_key() {
	gpg --keyserver hkp://pgp.mit.edu --send-keys "$key_to_sign"
}

main() {
	parse_args "$@"

	get_key
	sign_key
	send_key
}

main "$@"
