#!/bin/bash

namcap PKGBUILD
. PKGBUILD
makepkg -sf "$@"
if pacman -Qi "$pkgname" | grep -q 'Install Reas.*Explicit' ; then
	sudo pacman -U *.pkg.tar.xz --noconfirm
else
	sudo pacman -U *.pkg.tar.xz --asdeps --noconfirm
fi
echo
echo
namcap PKGBUILD
