#!/bin/bash

db=$1

if [[ -z "$db" ]] ; then
	echo >&2 'error: must specify db'
	exit 1
fi

base=${BASH_SOURCE[0]%/*}
docs_official=$base/../lists/official

while IFS= read -r pg ; do
	"$base/dbmod" "$db" group $pg blackarch
done < "$docs_official"
