#!/bin/bash

cd "${BASH_SOURCE[0]%/*}"

echo 'running get-real...'

#./get-real

echo 'checking signatures...'

cd ../real-repo

for i in */*.sig ; do
	gpg --with-fingerprint --verify "$i" /dev/null 2>&1 | grep -q EA87E4E3 || echo "wrong key: $i"
done
