#!/bin/python3

import requests
from concurrent.futures import ThreadPoolExecutor


BASE_URL="https://www.blackarch.org/blackarch/lastupdate"
MIRROR_LIST="https://raw.githubusercontent.com/BlackArch/blackarch/master/mirror/mirror.lst"
THX = 30


def check(sess, url, name, lastupdate):
  try:
    r = sess.get(url, stream=True)
    repo_statuscode = r.status_code
    repo_lastupdate = r.text

    if repo_lastupdate < lastupdate:
      print(f'[OUT OF DATE] - {name} -> {url}')
    elif repo_lastupdate > lastupdate:
      print(f'[SOMETHING IS WRONG] - {name} -> {url}')
    else:
      print(f'[IN SYNC] - {name} -> {url}')
  except:
    print(f'[HOST DOWN?] - {name} -> {url}')

  return


def main():
  #check_mirror(requests.get(MIRROR_LIST), requests.get(BASE_URL).text)
  sess = requests.Session()
  mirrorlist = sess.get(MIRROR_LIST)
  lastupdate = sess.get(BASE_URL).text

  with ThreadPoolExecutor(THX) as exe:
    for line in mirrorlist.iter_lines():
      try:
        country, url, name = str(line).split('|')
        name = name.strip('\'')
        url = url.replace("$repo/os/$arch", "lastupdate")
      except:
        print(f'[SOMETHING IS WRONG] Error: {line}.')

      exe.submit(check, sess, url, name, lastupdate)

  return


if __name__ == "__main__":
  main()

