#!/bin/bash

db_name=blackarch.db.tar.gz
db_link=blackarch.db
archs=(x86_64 i686)

base=$(dirname "$0")
real_local=$(realpath "$base/../real-repo")

for arch in "${archs[@]}" ; do
	echo >&2 "compiling $arch database..."
	cd "$real_local/$arch"

	rm -fv *.db*
	repo-add "$db_name" *.pkg.tar.xz

	# Sign.
	gpg -b "$db_name"
	ln -s "$db_name.sig" "$db_link.sig"
done
