#!/bin/bash

db_name=blackarch.db.tar.gz

base=$(dirname "$0")
real_local=$(realpath "$base/../real-repo")

for arch in x86_64 i686 ; do
	echo >&2 "compiling $arch database..."
	cd "$real_local/$arch"

	rm -fv *.db*
	repo-add "$db_name" *.pkg.tar.xz
done
