#!/bin/bash

err() {
	echo "ERROR: $*"
}

parse_args() {
	case "$1" in
		group)
			action=group
			package=$1
			groups+=("$@")
			if (( ${#groups[@]} == 0 )) ; then
				err 'no groups specified'
				exit 1
			fi
			;;
		*)
			err "invalid action: $1"
			exit 1
			;;
	esac
	shift
}

cleanup() {
	rm -rf "$tmp"
}

extract() {
	tmp=$(mktemp -d)
	tar xzf "$db_file" -C "$tmp"
}

take_action() {
	case "$action" in
		group)

			;;
	esac
}

archive() {
	( cd "$tmp"
	  tar czf "$db_file" * )
}

main() {
	parse_args "$@"

	extract
	take_action
	archive
}

main "$@"
