#!/bin/sh
# Increment $epoch for a package.

cd "$(dirname "$0")"

if [[ $# == 0 ]] ; then
	echo >&2 'no arguments.'
	exit 1
fi

pkgbuild=../packages/$1/PKGBUILD

. "$pkgbuild"

sed -i "/^epoch=/d
        /^pkgrel=/s/[0-9]\+/$(( pkgrel + 1 ))/
        /^pkgrel=/a\epoch=100" "$pkgbuild"
