#!/bin/bash

err=$1
out=$2

while IFS= read -r p ; do
	sed -n "/Making package: $p /,/Making package: /p" "$out" |
	  grep -q '==> ERROR: Could not resolve all dependencies.' &&
	  echo "dep: $p" ||
	  echo "err: $p"
done < "$err"
