#!/bin/bash
# Looks for a package in the following locations:
#  - BlackArch
#  - ArchTrack
#  - The official repos
#  - The AUR
#
# This script may be called from any location but the script itself must
#  live in '**/scripts'

pack=$1
basedir=$(dirname "$0")/..

# Look in BlackArch.
if [[ -d $basedir/packages/$pack ]] ; then
	echo 'Exists in BlackArch.'
	exit
fi

# Look in Broken
if [[ -d $basedir/broken/$pack ]] ; then
	echo 'Exists in Broken'
	exit
fi

# Look in ArchPwn
if [[ -d $basedir/archpwn/$pack ]] ; then
	echo 'Exists in Broken'
	exit
fi

# Look in official repos.
if pacman -Si $pack &> /dev/null ; then
	echo 'Exists in official repos.'
	exit
fi

# Look in the AUR.
if yaourt -Si $pack &> /dev/null ; then
	echo 'Exists in AUR.'
	exit
fi

echo 'Does not exist.'
