#!/bin/bash

cd "$(dirname "$0")/.."

site=blackarch.org
real_local=real-repo
sitedir=/var/www/blackarch.org/blackarch/blackarch/os

rsync -avz --delete-after \
  "${site:-safety}:${sitedir:-safety}/" "${real_local:-safety}"
