#!/bin/bash

cd "$(dirname "$0")/.."

site=blackarch.org
real_local=real-repo/os
sitedir=/nginx/var/www/blackarch/blackarch/os

rsync -avz --delete-after \
  "${site:-safety}:${sitedir:-safety}/" "${real_local:-safety}"
