#!/bin/bash
# Installs all package dependencies.
# Must be run from the repo root.

for pack in packages/*/PKGBUILD ; do (
	source "$pack"
	printf '%s\n' ${makedepends[@]} ${depends[@]}
) done | sort -u | xargs pacman --asdeps --needed --noconfirm -S
