#!/bin/bash

pkgbuild=$1

. "$pkgbuild"

for dep in "${depends[@]}" "${makedepends[@]}" ; do
	# Strip the version specifiers.
	dep=$(sed 's/\(>\|<\|=\).*//' <<< $dep)

	sudo pacman -S --needed --noconfirm --asdeps "$dep"
done
