#!/bin/bash
# Make symlinks in the real repo.

archs=(i686 x86_64)

cd "${0%/*}/../real-repo"

for arch in "${archs[@]}" ; do
	ln -fvs blackarch.files $arch/blackarch-testing.files
	ln -fvs blackarch.db $arch/blackarch-testing.db
	ln -fvs blackarch.db.sig $arch/blackarch-testing.db.sig
done
