#!/bin/bash
# Make symlinks in the real repo.

archs=(i686 x86_64)

cd "${0%/*}/../real-repo"

for arch in "${archs[@]}" ; do
	ln -fvs blackarch.files $arch/blackarchlinux.files
	ln -fvs blackarch.files $arch/blackarchlinux-testing.files
	ln -fvs blackarch.db $arch/blackarchlinux.db
	ln -fvs blackarch.db $arch/blackarchlinux-testing.db
done
