#!/bin/bash
# List packages in the real repo that no longer exist in the Git repo.

base=${BASH_SOURCE[0]%/*}/..
cd "$base"
docs_official=lists/official

pacman -Sql blackarch |
while IFS= read -r pack ; do
	if [[ ! -e "packages/$pack" ]] && ! grep -q "^$pack " "$docs_official" ; then
		echo "$pack"
	fi
done
