#!/bin/bash
# Lists packages that we need to add to BlackArch as dependencies or optional
#  dependencies for other packages. This script generally is mostly correct.
# This script may called from any location but the script itself must
#  live in '$projectroot/scripts'.

cd "$(dirname "$0")/.."

for package in packages/* archtrack/* ; do
	unset optdepends depends
	source "$package/PKGBUILD"
	printf '%s\n' "${optdepends[@]}" "${depends[@]}"
done | sed 's/\(>\|<\|:\).*//' | sort -u |
while read package ; do
	if ! pacman -Si $package &>/dev/null &&
		[[ ! -d packages/$package ]] ; then
		echo $package
	fi
done
