#!/bin/bash
# List packages in the real repo that no longer exist in the Git repo.

base=${BASH_SOURCE[0]%/*}/..
cd "$base"

pacman -Sql blackarch |
while IFS= read -r pack ; do
	if [[ ! -e "packages/$pack" ]] ; then
		echo "$pack"
	fi
done
