#!/bin/bash
# List packages in the real repo that no longer exist in the Git repo.

package=$1

base=$(dirname "$0")

get_name() {
	tar xJf "$1" .PKGINFO --force-local -O 2> /dev/null | grep '^pkgname' | cut -d' ' -f3
}

pkgname=$(get_name "$package")
if [[ ! -d ../packages/$pkgname ]] ; then
	echo "$package"
fi
