#!/bin/bash
# Provides some informative lists.
# Must be run from the root of the repository.

usage() {
	echo >&2 "Help will come soon. For now, look at the source."
}

cd "$(dirname "$0")/../packages"
case "$1" in
	p|packages)
		find . -name PKGBUILD
		;;
	a|all-groups)
		find . -name PKGBUILD | while read package ; do
			source "$package" &>/dev/null
			for group in ${groups[@]} ; do
				echo $group
			done
		done | sort -u
		;;
	s|straight-associations)
		find . -name PKGBUILD | while read package ; do
			source "$package" &>/dev/null
			for group in ${groups[@]} ; do
				[[ $group == archtrack ]] || echo "$group $package"
			done
		done | sort
		;;
	g|groupings)
		find . -name PKGBUILD | while read package ; do
			source "$package" &>/dev/null
			echo "$package ${groups[@]}"
		done | sort
		;;
	*)
		usage
		exit 1
		;;
esac
