#!/bin/bash

pacman -Sg | grep blackarch- |
while read group ; do
	case "$group" in
		blackarch-intel) name='Intelligence Gathering' ;;
		blackarch-forensics) name='Forensics' ;;
		blackarch-exploitation) name='Exploitation' ;;
		blackarch-defensive) name='Defensive' ;;
		blackarch-wireless) name='Wireless Attacks' ;;
		blackarch-analysis) name='Threat Analysis' ;;
		blackarch-web-apps) name='Web Applications' ;;
		blackarch-password-attacks) name='Password Attacks' ;;
		blackarch-hardware-hacking) name='Hardware Hacking' ;;
		blackarch-reversing) name='Reverse Engineering' ;;
		blackarch-stress-testing) name='Stress Testing' ;;
		blackarch-threat-model) name='Threat Modeling' ;;
	esac

	cat <<-EOF
	#### $name
	 \`\`\`
	 # pacman -S $group
	 \`\`\`

	Tools in this group:

	EOF
	pacman -Sgg | grep "^$group" | cut -d' ' -f2 |
	while read pack ; do
		echo "  - $pack"
	done

	echo
done
