#!/bin/bash

db_name=blackarch.files.tar.gz

base=$(dirname "$0")
real_local=$(realpath "$base/../real-repo")

for arch in x86_64 i686 ; do
	cd "$real_local/$arch"

	echo >&2 "compiling $arch files database..."

	rm -v *.files*
	repo-add -f "$db_name" *.pkg.tar.xz
done
