#!/bin/bash

cd "$(dirname "$0")"/..
mv database database.old
mkdir database
# Includes signatures
cp packages/*/*.pkg.* database
cd database
repo-add archtrack.db.tar.gz -k archtrack -s *.pkg.tar.xz
