#!/bin/bash

pacman -Sg | grep blackarchlinux- |
while read group ; do
	case "$group" in
		blackarchlinux-intel) name='Intelligence Gathering' ;;
		blackarchlinux-forensics) name='Forensics' ;;
		blackarchlinux-exploitation) name='Exploitation' ;;
		blackarchlinux-defensive) name='Defensive' ;;
		blackarchlinux-wireless) name='Wireless Attacks' ;;
		blackarchlinux-analysis) name='Threat Analysis' ;;
		blackarchlinux-web) name='Web Applications' ;;
		blackarchlinux-password-attacks) name='Password Attacks' ;;
		blackarchlinux-hardware-hacking) name='Hardware Hacking' ;;
		blackarchlinux-reversing) name='Reverse Engineering' ;;
		blackarchlinux-stress-testing) name='Stress Testing' ;;
		blackarchlinux-threat-model) name='Threat Modeling' ;;
		blackarchlinux-windows) name='Windows' ;;
        blackarchlinux-drone) name'BlacArchLinux Drones' ;;

		*) echo "unknown group: $group"; exit 1 ;;
	esac

	cat <<-EOF
	#### $name
	 \`\`\`
	 # pacman -S $group
	 \`\`\`

	Tools in this group:

	EOF
	pacman -Sgg | grep "^$group" | cut -d' ' -f2 |
	while read pack ; do
		echo "  - $pack"
	done

	echo
done
