#!/bin/bash

cd "$(dirname "$0")/.."

dir=menu

mkdir -p "$dir"

for p in packages/* ; do (
	. "$p/PKGBUILD"

	while read name exec term ; do
		cat >> "$dir/$name.desktop" <<-EOF
		[Desktop Entry]
		Name=$name
		Encoding=UTF-8
		Exec=$exec
		Icon=blackarch-menu.png
		StartupNotify=false
		Terminal=false
		Type=Application
		Categories=${groups// /:}
		X-Blackarch-Package=$pkgname
		EOF
	done < "$p/bin"
) done
