#!/bin/bash

basedir=$(dirname "$0")
script=${1:-install-gems}

cat > "$script" <<\EOF
#!/bin/bash

# Install bundler if it is not already installed.
gem list | grep -q '^bundler\s' || gem install bundler

do_install() {
	cd "/usr/share/$1"
	bundle install
}

EOF

grep -l 'depends.*ruby' "$basedir"/../packages/*/PKGBUILD |
while read pkgbuild ; do
	pack=$(basename "$(dirname $pkgbuild)")
	echo >&2 "adding $pack..."
	echo "do_install $pack" >> "$script"
done

echo >&2 "made script at $script."
chmod +x "$script"
