#!/bin/bash
# Lists $pkgname / directory name mismatches

cd "$(dirname "$0")/../packages"

error=0

for p in * ; do (
	. "$p/PKGBUILD"
	if [[ "$pkgname" != "$p" ]] ; then
		echo "pkgname '$pkgname' does not match directory '$p'"
		error=1
	fi
) done

exit $error
