#!/bin/bash
# Lists $pkgname / directory name mismatches

cd "$(dirname "$0")/../packages"

error=0

for p in * ; do (
	. "$p/PKGBUILD" || continue
	if [[ -n "$pkgbase" ]] ; then
		name=$pkgbase
	else
		name=$pkgname
	fi
	if [[ "$name" != "$p" ]] ; then
		echo "pkgname '$name' does not match directory '$p'"
		error=1
	fi
) done

exit $error
