#!/bin/bash
# Cleans up PKGBUILD files.
# Spots that need manual checking are marked with 'TODO'

for pkgbuild ; do
	if [[ ! -r "$pkgbuild" ]] ; then
		echo >&2 "could not read '$pkgbuild'."
		exit 1
	fi
	echo "cleaning '$pkgbuild'..."

	# Expand tabs
	echo "expanding tabs..."
	expand -it2 "$pkgbuild" | sponge "$pkgbuild"

	# Remove vim modeline
	echo "removing vim modeline..."
	sed -i '/#\s*vim:/d' "$pkgbuild"

	# Remove maintainer and contributor comments
	echo 'removing contributor and maintainer comments...'
	sed -i '/#\s*\([Cc]ontributor\|[Mm]aintainer\)/d'

	# Squeeze extra blank lines (why does cat have this feature?)
	echo 'squeezing extra blank lines...'
	cat -s "$pkgbuild" | sponge "$pkgbuild"

	# Remove '|| return'
	echo "removing '|| return'..."
	sed -i 's/||\s*return.*//' "$pkgbuild"

	# Check for package function
	if ! grep -q 'package()' "$pkgbuild" ; then
		sed -i '1i\# TODO: make package function' "$pkgbuild"
		echo "warning: no package function"
	fi

	# Remove trailing whitespace
	if grep -Eq '[[:space:]]+$' "$pkgbuild" ; then
		echo "removing trailing whitespace..."
		sed -i 's/[[:space:]]+$//' "$pkgbuild"
	fi

	# Check for startdir
	# This is too difficult to fix automatically
	if grep -q 'startdir' "$pkgbuild" ; then
		echo 'warning: has startdir'
		sed -i '1i\# TODO: remove startdir' "$pkgbuild"
	fi
done
