#!/bin/bash
# Cleans up pkgbuild_tmp files.
# Spots that need manual checking are marked with 'TODO' comments.

# Simulates sponge from moreutils
_sponge() {
	tmp=$(mktemp /tmp/blackarch-prep.XXXXXXXXX)
	cat > "$tmp"
	mv "$tmp" "$1"
}

err() {
	echo >&2 "$*"
}

pkgbuild_tmp=$(mktemp /tmp/blackarch-prep.XXXXXXXX)
trap "rm -f $pkgbuild_tmp" EXIT

if (( $# <= 1 )) ; then
	cat > "$pkgbuild_tmp"
	output=/dev/stdout
else
	cat "$1" > "$pkgbuild_tmp"
	output=$1
fi

source "$pkgbuild_tmp"
namcap "$pkgbuild_tmp"

if [[ ! -r "$pkgbuild_tmp" ]] ; then
	err "could not read '$pkgbuild_tmp'."
	exit 1
fi
err "cleaning '$pkgbuild_tmp'..."

# Expand tabs to two spaces
err "expanding tabs..."
expand -it2 "$pkgbuild_tmp" | _sponge "$pkgbuild_tmp"

# Remove vim modeline
err "removing vim modeline..."
sed -i '/#\s*vim:/d' "$pkgbuild_tmp"

# Check license
#err "checking license..."
#for lic in "${license[@]}" ; do
#	if [[ ! "$lic" =~ \
#		   ^([Uu]nknown|[Cc]ustom.*|BSD|MIT|ZLIB|[Pp]ython)$ ]] ; then
#		[[ -z "$lic" ]] && err "'$pkgbuild_tmp' has no license."
#		[[ -e /usr/share/licenses/common/$lic ]] ||
#		err "'$pkgbuild_tmp' has invalid license: '$lic'"
#		sed -i '1i\# TODO: check license' "$pkgbuild_tmp"
#	fi
#done

# Remove Id comment
err "removing id comment..."
sed -i '/#\s*\$\s*Id:/d' "$pkgbuild_tmp"

# Remove maintainer and contributor comments
err 'removing contributor and maintainer comments...'
sed -i '/#\s*\([Cc]ontributor\|[Mm]aintainer\)/d' "$pkgbuild_tmp"

# Squeeze extra blank lines (why does cat have this feature?)
err 'squeezing extra blank lines...'
cat -s "$pkgbuild_tmp" | _sponge "$pkgbuild_tmp"

# Remove '|| return'
err "removing '|| return'..."
sed -i 's/||\s*return.*//' "$pkgbuild_tmp"

# Check for package function
if ! grep -q 'package.*()' "$pkgbuild_tmp" ; then
	err "warning: no package function"
	sed -i '1i\# TODO: make package function' "$pkgbuild_tmp"
fi

# Remove blank line at top
# This also adds a trailing newline if there isn't one already.
err 'removing leading blank line...'
awk 'BEGIN{ i=0 } {
		if (!(/^$/ && i==0)) {
		   print
		}
		i++
	 }' "$pkgbuild_tmp" | _sponge "$pkgbuild_tmp"

# Check for startdir
# This is too difficult to fix automatically
if grep -q 'startdir' "$pkgbuild_tmp" ; then
	err 'warning: has startdir'
	sed -i '1i\# TODO: remove startdir' "$pkgbuild_tmp"
fi

# Remove $pkgname
if grep -q '\$pkgname' "$pkgbuild_tmp" ; then
	err 'removing $pkgname...'
	sed -i "s/\\\$pkgname/$pkgname/g" "$pkgbuild_tmp"
fi

# Remove trailing whitespace
if grep -Eq '[[:space:]]+$' "$pkgbuild_tmp" ; then
	err 'removing trailing whitespace...'
	sed -i 's/[[:space:]]*$//' "$pkgbuild_tmp"
fi

cat "$pkgbuild_tmp" > "$output"
