#!/bin/bash
DIRLIST=$(find . -maxdepth 1 -mindepth 1 -type d -name "ruby-*" -printf '%f\n' | cut -d "-" -f2)
update()
{
	curl -s https://rubygems.org/api/v1/gems/"$1".xml | grep -oP '(?<=<version>).*?(?=</version)'
	echo $1
}

for i in $DIRLIST; do
	update $i
done
