#!/bin/bash

base=$(realpath "$(dirname "$0")")
archs=(x86_64 i686)

cd "$base/.."

real_local=real-repo

for arch in "${archs[@]}" ; do (
	cd "$real_local/$arch"

	rm *.sig
	"$base/sign" *.pkg.tar.xz
) done
