#!/bin/bash

base=$(realpath "$(dirname "$0")")

cd "$base/.."

real_local=real-repo
db_name=blackarch.db.tar.gz
db_link=blackarch.db

for arch in x86_64 i686 ; do (
	cd "$real_local/$arch"

	rm *.sig
	"$base/sign" *.pkg.tar.xz "$db_name"
	ln -s "$db_name.sig" "$db_link.sig"
) done
