#!/bin/sh

BASE=${PWD}/${BASH_SOURCE[0]%/*}
LOG="${BASE}/../lists/to-release"

EX='apacket blackbox-scanner bof-detector brutexss cheetah-suite cjexploiter
crozono cybercrowl darkspiritz d-tect exploitpack findmyiphone flamerobin ftpmap
gloom grabing htrosbif icloudbrutter junkie l0l ld-shatner levye liffy loot
maryam mooscan mysql2sqlite neglected netcommander osinterator owasp-bywaf
paraxor-dwm paraxor-slock paraxor-st passcracking peda pykek proctal
python2-ctags revipd riwifshell routerhunter sb0x sea search1337 sees shitflood
slurp slowloris-py smap smbexec smod smplshllctrlr sniffer sqlmap subbrute
sysdig treasure valabind visql weeman'

rm -f $LOG

cd "${BASE}/../packages"

pkgs=$(grep -r "^source=(.*['\"]git" * | cut -d '/' -f 1 | tr -s '\n' ' ' |
  sort -u)

for e in $EX
do
  pkgs=$(echo $pkgs | sed "s/\<$e\>//g")
done

for pkg in $pkgs
do
  echo "    > $pkg "
  cd "${BASE}/../packages/$pkg"
  makepkg -od > /dev/null 2>&1
  cd "${BASE}/../packages"
done

git add . 2> /dev/null
git commit -m 'git packages: version bumps' . 2> /dev/null
git push 2> /dev/null

lastcommit=$(git rev-parse --verify HEAD)
files=$(git diff-tree --no-commit-id --name-only -r $lastcommit |
  sed -E 's/packages\/|\/PKGBUILD//g')

echo
echo "last commit hash:"
echo $lastcommit
echo
echo "tools updated:"
echo $files | tr -s ' ' '\n' | tee -a $LOG

# EOF
