#!/bin/sh

BASE=${PWD}/${BASH_SOURCE[0]%/*}
LOG="${BASE}/../lists/to-release"

EX='apacket apt2 autonse autovpn blackbox-scanner blackeye bof-detector brutexss
cheetah-suite citadel cjexploiter cmsfuzz crozono cybercrowl darkspiritz dagon
d-tect entropy evilpdf exploitpack facebash findmyiphone flamerobin ftpmap
ghostdelivery gloom grabing graffiti hiddeneye htrosbif icloudbrutter instashell
konan junkie jooforce jsearch l0l ld-shatner leroy-jenkins levye liffy loot
maigret maryam mooscan multitun mysql2sqlite neglected netcommander osinterator
owasp-bywaf paraxor-dwm paraxor-slock paraxor-st passcracking peda pepe
phonesploit phonia powerops pureblood pykek proctal python2-ctags pwdlyser
revipd riwifshell routerhunter sb0x sea search1337 sees shitflood simple-ducky
skiptracer slurp slowloris-py smap smbexec smod smplshllctrlr sniffer sqlmap
subbrute swamp sysdig treasure tweetshell ultimate-facebook-scraper userrecon-py
userrecon valabind visql wascan weeman whatbreach wpseku xss-freak zeus-scanner'

rm -f $LOG

cd "${BASE}/../packages"

#pkgs=$(grep -r "^source=(.*['\"]git" * | cut -d '/' -f 1 | tr -s '\n' ' ' |
pkgs=$(grep -r "^source=(.*['\"::]git\+" * | cut -d '/' -f 1 | tr -s '\n' ' ' |
  sort -u)

for e in $EX
do
  pkgs=$(echo $pkgs | sed "s/\<$e\>//g")
done

for pkg in $pkgs
do
  echo "    > $pkg "
  cd "${BASE}/../packages/$pkg"
  makepkg -od > /dev/null 2>&1
  cd "${BASE}/../packages"
done

git add . 2> /dev/null
git commit -m 'git packages: version bumps' . 2> /dev/null
git push 2> /dev/null

lastcommit=$(git rev-parse --verify HEAD)
files=$(git diff-tree --no-commit-id --name-only -r $lastcommit |
  sed -E 's/packages\/|\/PKGBUILD//g')

echo
echo "last commit hash:"
echo $lastcommit
echo
echo "tools updated:"
echo $files | tr -s ' ' '\n' | tee -a $LOG

# EOF
