#!/bin/sh
#
# !!! CAUTION !!!
#
# this script is not finished yet. do not use it!
#
# !!! CAUTION !!!
#
# TODO:
#   - use 'git ls-remote $URL HEAD' instead of makepkg -o. thanks to elken.

# upgrade-git-pkg version
VERSION="upgrade-git-pkgs v0.4.1"

# true / false
FALSE=0
TRUE=1

# return codes
SUCCESS=1337
FAILURE=31337

# verbose mode - default: quiet
VERBOSE="/dev/null"

# skip update version step (makepkg -o)
SKIP_UPDATE=$FALSE

# dry-run: list packages that have to be upgraded
LIST_UPGRADES=$FALSE

# default exclude packages
EXCLUDES="impacket ipmitool ld-shatner levye liffy loot masscan metasploit"
EXCLUDES="${EXCLUDES} mysql2sqlite neglected netcommander osinterator"
EXCLUDES="${EXCLUDES} owasp-bywaf peda passcracking python2-ctags radare2"
EXCLUDES="${EXCLUDES} ropper sb0x scrapy sqlmap subbrute sysdig treasure"
EXCLUDES="${EXCLUDES} valabind webxploiter"

# new to build and release packages
PKGS=""


# print warning
warn()
{
    echo "[!] WARNING: ${@}"

    return $SUCCESS
}


# print error and exit
err()
{
    echo "[-] ERROR: ${@}"
    exit $FAILURE

    return $SUCCESS
}


# exclude given packages
exclude_packages()
{
    echo "[+] excluding given packages"

    for ex in ${EXCLUDES}
    do
        echo "    > ${ex}"
        sed -i "/\<${ex}\>/d" /tmp/git-packages
    done

    return $SUCCESS
}


# get git based packages
get_git_packages()
{
    echo "[+] getting git packages"

    pkgs=`grep -r "^source=(.*['\"]git" * | cut -d '/' -f 1 | tr -s '\n' ' ' |
    sort -u`

    rm /tmp/git-packages > ${VERBOSE} 2>&1

    for pkg in ${pkgs}
    do
        ver="`pacman -Si ${pkg} | sed -n '/: blackarch/,/Description:/p' |
        grep '^Version' | cut -d ':' -f 2- | sed 's/.//'`"
        echo "${pkg} ${ver}" >> /tmp/git-packages
        sort -u /tmp/git-packages -o /tmp/git-packages
    done

    return $SUCCESS
}


# update git version number
update_version()
{
    if [ $SKIP_UPDATE -eq $FALSE ]
    then
        echo "[+] updating version numbers"

        for pkg in `cut -d ' ' -f 1 /tmp/git-packages`
        do
            echo "    > ${pkg}"
            cd ${pkg}
            makepkg -o > ${VERBOSE} 2>&1
            rm -rf src
            cd ..
        done
    else
        warn "skipping version update step"
    fi

    return $SUCCESS
}


# compare updated git version number with old one
cmp_version()
{
    echo "[+] comparing version numbers"

    for p in ${pkgs}
    do
        pkg="`cut -d ' ' -f 1 /tmp/git-packages | grep ${p}`"
        old="`grep ${p} /tmp/git-packages | cut -d ' ' -f 2 |
        cut -d ':' -f 2- |cut -d '-' -f 1`"
        new="`grep -r "^pkgver=" ${p} | cut -d '=' -f 2 | tr -d "'"`"

        if [ "${new}" != "${old}" ]
        then
            if [ $LIST_UPGRADES -eq $TRUE ]
            then
                echo "    > upgrade: ${p} (${old} -> ${new})"
            else
                sed -i 's/pkgrel=.*/pkgrel=1/' ${p}/PKGBUILD
                PKGS="${PKGS} ${p}"
            fi
        else
            echo "    > skipping ${p}" > $VERBOSE 2>&1
        fi
    done

    return $SUCCESS
}


# build packages
build_packages()
{
    echo "[+] upgrading packages"

    for p in ${PKGS}
    do
        sudo rm -rf /tmp/${p} > $VERBOSE 2>&1
        sudo ${base}/../scripts/babuild -g "${p}" -o "/tmp/${p}" \
            -p "${name}" \
        2> $VERBOSE
    done

    return $SUCCESS
}


# release packages
release_packages()
{
    echo "[+] releasing packages"

    for p in ${PKGS}
    do
        ${base}/../scripts/barelease -u ${user} -k ${key} -f -w /tmp/${p}/* \
        2> $VERBOSE
    done

    return $SUCCESS
}


# usage and help
usage()
{
    echo "usage:"
    echo ""
    echo "  upgrade-git-pkgs -u <arg> -k <arg> -n <arg> [options] | <misc>"
    echo ""
    echo "options:"
    echo ""
    echo "  -u <user>   - username for babuild/barelease"
    echo "  -k <keyid>  - gpg key id for babuild/barelease"
    echo "  -n <name>   - your real name for package signing (e.g.: 'Foo bar')"
    echo "  -e <pkgs>   - exclude given packages (e.g.: foo,bar,foobar)"
    echo "  -s          - skip updating versions step (default: off)"
    echo "  -l          - dry-run, do not upgrade just list the packages"
    echo "  -v          - verbose mode (default: off)"
    echo ""
    echo "misc:"
    echo ""
    echo "  -V          - print version of upgrade-git-pkg and exit"
    echo "  -H          - print this help and exit"

    exit $SUCCESS

    return $SUCCESS
}


# check argument count
check_argc()
{
    if [ ${#} -lt 1 ]
    then
        err "-H for help and usage"
    fi

    return $SUCCESS
}


# check if required arguments were selected
check_args()
{
    if [ "${user}" = "" ]
    then
        err "no username given"
    fi

    if [ "${key}" = "" ]
    then
        err "no gpg keyid given"
    fi

    if [ "${name}" = "" ]
    then
        err "no realname given"
    fi

    return $SUCCESS
}


# parse command line options
get_opts()
{
    while getopts u:k:n:e:slvVH flags
    do
        case ${flags} in
            u)
                user="${OPTARG}"
                ;;
            k)
                key="${OPTARG}"
                ;;
            n)
                name="${OPTARG}"
                ;;
            e)
                EXCLUDES="${EXCLUDES} `echo ${OPTARG} | tr -s ',' ' '`"
                ;;
            s)
                SKIP_UPDATE=$TRUE
                ;;
            l)
                LIST_UPGRADES=$TRUE
                ;;
            v)
                VERBOSE="/dev/stdout"
                ;;
            V)
                echo "${VERSION}"
                exit $SUCCESS
                ;;
            H)
                usage
                ;;
            *)
                err "WTF?! mount /dev/brain"
                ;;
        esac
    done

    return $SUCCESS
}


# controller and program flow
main()
{
    base=${BASH_SOURCE[0]%/*}

    cd "${base}/../packages"

    check_argc "${@}"
    get_opts "${@}"
    check_args "${@}"
    get_git_packages
    exclude_packages
    update_version
    cmp_version
    build_packages
    release_packages

    return $SUCCESS
}


# program start
main "${@}"

# EOF
