post_install() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  echo 'If you use a lightweight windowmanager, remember to run'
  echo '/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 to enable'
  echo 'graphical authentication, which may be needed for pkexec to work.'
}

post_upgrade() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_remove() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
