# arg 1:  the new package version
post_install() {
  KERNEL_VERSION='2.6.28-ARCH'
  depmod -ae -v $KERNEL_VERSION  > /dev/null 2>&1		 
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  KERNEL_VERSION='2.6.28-ARCH'
  depmod -ae -v $KERNEL_VERSION	 > /dev/null 2>&1	 
  
}

# arg 1:  the old package version
post_remove() {
  KERNEL_VERSION='2.6.28-ARCH'
  depmod -ae -v $KERNEL_VERSION	 > /dev/null 2>&1	 
}

op=$1
shift
$op $*
