#!/bin/bash

if [ -x /usr/lib/jvm/java-1.6.0-openjdk/bin/java ];then
       /usr/lib/jvm/java-1.6.0-openjdk/bin/java -jar /usr/share/java/ipscan/ipscan-linux-3.0-beta4.jar
else
  echo;echo "Warning: Couldn't find the correct java-version (openjdk6) in it's path /usr/lib/jvm/java-1.6.0-openjdk/bin/java. Falling back to $$PATH/java. if it doesn't work please correct this symlink to point to a recent free java version like openjdk/icedtea or a proprietary one."	
  java -jar /usr/share/java/ipscan/ipscan-linux-3.0-beta4.jar
fi
