#!/bin/bash
i686=true
x86_64=true

for arg ; do
	case arg in
		-i|--i686)
			i686=true
			x86_64=false
			;;
		-x|--x86_64)
			i686=false
			x86_64=true
			;;
	esac
done

$i686 && makepkg --config "$(dirname "$0")/conf/makepkg.x86_64.conf" 2>&1 | tee -a builds.log
$x86_64 && makepkg --config "$(dirname "$0")/conf/makepkg.i686.conf" 2>&1 | tee -a builds.log
