name: CI
on:
  push:
    branches: [master]
    paths:
      - 'packages/**'
  pull_request:
    branches: [master]
    paths:
      - 'packages/**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft
env:
  HEAD_REF: ${{ github.event.pull_request.head.ref }}             # <branch> (e.g., patch-1)
  HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }} # <user>/blackarch
  HEAD_SHA: ${{ github.event.pull_request.head.sha }} 

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    container:
      image: blackarchlinux/blackarch:latest
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm --needed git pkgcheck-arch namcap nodejs python3
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.HEAD_REF }}
          repository: ${{ env.HEAD_REPO }}
          fetch-depth: 0
      - name: Set up remotes and tags
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git remote add upstream "https://github.com/BlackArch/blackarch.git" 2>/dev/null || true
          git fetch --tags origin || true
          git fetch upstream master || true
      - name: Run BlackArch Package Verification
        run: |
          python3 scripts/bautil.py check
          CHANGED_FILES=($(git diff --name-only --diff-filter=ACMRT upstream/master...${{ env.HEAD_SHA }} 2>/dev/null | tr '\n' ' '))
          for FILE in "${CHANGED_FILES[@]}"; do
             if [[ $(basename "$FILE") == "PKGBUILD" ]]; then
               echo "Validating $FILE..."
               pkgcheck "$FILE"
             fi
          done
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
         with:
           ref: ${{ env.HEAD_REF }}
           repository: ${{ env.HEAD_REPO }}
           fetch-depth: 0
       - name: Set up remotes and tags
         run: |
           git config --global --add safe.directory "$GITHUB_WORKSPACE"
           git remote add upstream "https://github.com/BlackArch/blackarch.git" 2>/dev/null || true
           git fetch --tags origin || true
           git fetch upstream master || true          
       - name: Build Package
         run: |
           CHANGED_FILES=($(git diff --name-only --diff-filter=ACMRT upstream/master...${{ env.HEAD_SHA }} 2>/dev/null | tr '\n' ' '))
           for FILE in "${CHANGED_FILES[@]}"; do
              if [[ $(basename "$FILE") == "PKGBUILD" ]]; then
                echo "Building $FILE..."
                docker build --load -t builder -f travis/Dockerfile $(dirname "$FILE")
                docker run --rm builder
              fi
           done
