name: CI
on:
  push:
    branches: [master]
    paths:
      - 'packages/**'
  pull_request:
    branches: [master]
    paths:
      - 'packages/**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    container:
      image: blackarchlinux/blackarch:latest
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm --needed git pkgcheck-arch
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - name: Check Styling
        run: |
           CHANGED_FILES=($(git diff --name-only --diff-filter=ACMRT origin/${{ github.event.pull_request.base.ref }}...${{ github.event.pull_request.head.sha }} | tr '\n' ' '))
           for FILE in "${CHANGED_FILES[@]}"; do
              if [[ $(basename $FILE) == "PKGBUILD" ]]; then
                echo "Validating $FILE..."
                pkgcheck $FILE
              fi
           done
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v5
         with:
           ref: ${{ github.event.pull_request.head.ref }}
           repository: ${{ github.event.pull_request.head.repo.full_name }}
           fetch-depth: 0
           
       - name: Build Package
         run: |
           CHANGED_FILES=($(git diff --name-only --diff-filter=ACMRT origin/${{ github.event.pull_request.base.ref }}...${{ github.event.pull_request.head.sha }} | tr '\n' ' '))
           for FILE in "${CHANGED_FILES[@]}"; do
              if [[ $(basename $FILE) == "PKGBUILD" ]]; then
                echo "Building $FILE..."
                docker build --load -t builder -f travis/Dockerfile $(dirname $FILE)
                docker run --rm builder
              fi
           done
