#!/bin/bash
echo "username: admin"
echo "pass: warvox"
# idea stolen from pentoo http://trac.pentoo.ch/browser/genmenu/trunk/src/share/genmenu/scripts/ntop
launchff() {
  sleep 10
  firefox http://127.0.0.1:7777/
}

launchff &
cd /usr/share/warvox/bin
./warvox.rb
